name: Build, Test

# Триггер для запуска пайплайна
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Задача запускается на ОС ubuntu
    runs-on: ubuntu-latest

    steps:
      # Это действие извлекает ваш репозиторий из папки $GITHUB_WORKSPACE,
      #  чтобы ваш рабочий процесс мог получить к нему доступ.
      - uses: actions/checkout@v3

      # Настройки java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      # Права на запуск gradlew
      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # билд проекта
      - name: Build project
        run: ./gradlew build


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      # Тест проекта
      - name: Run tests
        run: ./gradlew test